### ISSUE TITLE
ClassNotFoundException using HudsonTestCase

### ISSUE THREAD

**Issue by quidryan** [jenkinsci/gradle-jpi-plugin#1]
This is the error I get when trying to run a unit test following https://wiki.jenkins-ci.org/display/JENKINS/Unit+Test:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestGroovy'.
> hudson/tasks/Ant$AntInstallation
```

This is my simple test class:

```
package javaposse.jobdsl.plugin;
import org.jvnet.hudson.test.HudsonTestCase;
public class SeedJobTest extends HudsonTestCase {
}
```

The requisite class is in ant-1.1.hpi.  My theory is that the hpi is being added to the classpath, but uselessly so. Since it has their .class files hidden in WEB-INF/classes, which is great for a war, but sucky for a classpath. I have no idea how to get around this, except to look at how the Maven plugin does it. 

junit4 unit tests with "public JenkinsRule j = new JenkinsRule();" work just fine.

**Comment by sghill** [comment]
I've recently enabled Github Issues and noticed this was still open. I'm going to close this issue since Gradle, this plugin, the linked docs, and Jenkins have all changed significantly since opening.
