### ISSUE TITLE
Option to allocate more resources to local jenkins to make the UI more responsive

### ISSUE THREAD

**Issue by skirdey** [jenkinsci/gradle-jpi-plugin#134]
It would be great if we could pass at least cpu/memory options when running jenkins server locally.

**Comment by sghill** [comment]
Hi @skirdey,

Thanks for raising this!

Is this for when running the plugin’s `server` task? If so, today that’s being executed in the same process as the daemon. [Adding more memory to the daemon](https://docs.gradle.org/current/userguide/build_environment.html) should make it available to Jenkins as well.

What’s the behavior you’re seeing with cpu usage?

**Comment by skirdey** [comment]
Hey hey, let me try adding more memory to the daemon. 
So far everything works perfect, it just the UI feels a bit slow when executing server task. 
If memory change does the trick I'll open a PR to document it.

**Comment by sghill** [comment]
Hi @skirdey, did you get a chance to try out these memory settings?

**Comment by skirdey** [comment]
org.gradle.jvmargs=-Xmx4096m

in gradle.properties

did the trick

**Comment by sghill** [comment]
Thanks for the followup @skirdey. I've added a note to the README, but feel free to send over a PR if you think it could be clearer.
