### ISSUE TITLE
Applying JpiPlugin fails when Jpi task is created during configuration phase

### ISSUE THREAD

**Issue by rpalcolea** [jenkinsci/gradle-jpi-plugin#141]
Hi!

I haven't found a way to reproduce this as I need to track down which plugin is making `Jpi` task to be created during configuration phase but when this happens, the following error happens:

```
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with type class org.jenkinsci.gradle.plugins.jpi.JpiPlugin has not been used.
        at org.gradle.api.internal.plugins.DefaultPluginContainer.getPlugin(DefaultPluginContainer.java:140)
        at org.gradle.api.plugins.PluginContainer$getPlugin$2.call(Unknown Source)
        at org.jenkinsci.gradle.plugins.jpi.JpiPlugin$_configureJpi_closure10.doCall(JpiPlugin.groovy:178)
```

Looking at https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy#L171

the usage of `it.classpath(jar, project.plugins.getPlugin(JpiPlugin).dependencyAnalysis.allLibraryDependencies)` is new and it breaks when eager creation/configuration of task happens. 

My theory is that if some other plugin or part of the build modifies all `War` tasks before the plugin is totally applied, it fails. I don't know how to about this since it seems wrong to do a `plugins.withType` for the same plugin before creating the task. 

While using task registration and lazy init is the ideal world. The truth is that several plugins force tasks to be created eagerly. I believe the plugin should handle that case. What are your thoughts @sghill? Do you have any suggestion for this?

**Comment by sghill** [comment]
Hi @rpalcolea,

Thanks for opening the issue. This really adds value to producing release candidates.

Is this using 0.39.0-rc.3 of gradle-jpi-plugin? What version of Gradle?

> The truth is that several plugins force tasks to be created eagerly. I believe the plugin should handle that case. What are your thoughts @sghill?

Yes, the plugin should work in this case.

> Do you have any suggestion for this?

Let's start with getting a reproducible example. I think the specifics on Gradle and plugin version will be a good start to creating one.

**Comment by rpalcolea** [comment]
Hey @sghill,

yeah so this is with 0.39.0-rc.3 and gradle 6.2

I created a test that reproduces the issue in https://github.com/jenkinsci/gradle-jpi-plugin/commit/869a52bb00922f5120cb396cc8ab1215511db81b

Basically, if you have a plugin that modifies `War` tasks (same type as `jpi` task) and it is applied before `JpiPlugin` in the build file, it fails with `Plugin with type class org.jenkinsci.gradle.plugins.jpi.JpiPlugin has not been used`

**Comment by sghill** [comment]
Great, thank you! I’ll have a look at this soon.

@wolfs @jjohannes have you seen this issue with plugin ordering before?

**Comment by jjohannes** [comment]
I see. I think it was not smart to use `plugins.getPlugin(JpiPlugin)` in code that is added during `apply()` and could be triggered right away.

I think we can replace all `project.plugins.getPlugin(JpiPlugin).dependencyAnalysis` with just an access to the `dependencyAnalysis` field by making the methods that use that **not** static.

**Comment by jjohannes** [comment]
@rpalcolea Can you check if this fixes the issue for your: https://github.com/jjohannes/gradle-jpi-plugin/commit/05df47822210ea69d2b896d401da5b08c56940f6 (and maybe create a PR with that and your test if it does)
