### ISSUE TITLE
JpiVariantRule breaks when a dependency comes from Ivy

### ISSUE THREAD

**Issue by rpalcolea** [jenkinsci/gradle-jpi-plugin#142]
After spending some time to fix eager jar/war task creation on our side, I found the following error:

```
Caused by: groovy.lang.MissingPropertyException: No such property: packaging for class: org.gradle.internal.component.external.model.ivy.DefaultIvyModuleResolveMetadata
        at org.jenkinsci.gradle.plugins.jpi.JpiVariantRule.isJenkinsPackaging(JpiVariantRule.groovy:70)
        at org.jenkinsci.gradle.plugins.jpi.JpiVariantRule.execute(JpiVariantRule.groovy:20)
        at org.jenkinsci.gradle.plugins.jpi.JpiVariantRule.execute(JpiVariantRule.groovy)
        at org.gradle.internal.action.InstantiatingAction.execute(InstantiatingAction.java:61)
        ... 187 more
``` 

`DefaultIvyModuleResolveMetadata` is the lazy representation of `IvyModuleResolveMetadata` which is Meta-data for a component resolved from an Ivy repository. Checking for jenkins and jar packaging assumes that `packaging` property is part of `ComponentMetadataContext.metadata` which isn't on this case.

I thought on adding the following to the `JpiVariantRule` 

```
 @Override
    void execute(ComponentMetadataContext ctx) {
        def id = ctx.details.id
        if(ctx instanceof DefaultIvyModuleResolveMetadata) {
            addEmptyJpiVariant(ctx)
        } else if (isJenkinsPackaging(ctx)) {
...
```

However, this is just to short circuit this issue  and assume that anything coming from Ivy is a Jar

Thoughts on this one @sghill @jjohannes

**Comment by rpalcolea** [comment]
I created a test that reproduces the issue: https://github.com/jenkinsci/gradle-jpi-plugin/commit/c2db2975c81e07621f9002dc7cb18441aaf22b4b -> https://github.com/jenkinsci/gradle-jpi-plugin/pull/143

Also I just noticed this: https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/LicenseTask.groovy#L80

Wondering if this will pickup dependencies coming from ivy repos and add them to the license as POMs.

**Comment by sghill** [comment]
> However, this is just to short circuit this issue and assume that anything coming from Ivy is a Jar

I think that's probably a reasonable assumption if it works internally. I don't know of anyone else using ivy repositories with this plugin.

> Wondering if this will pickup dependencies coming from ivy repos and add them to the license as POMs.

It actually just fails with a 404 for the referenced POM and must be disabled if any ivy repos have been declared. [JENKINS-51620](https://issues.jenkins-ci.org/browse/JENKINS-51620) captures this and the workaround of disabling the `generateLicenseInfo` task.

**Comment by rpalcolea** [comment]
I wonder if gradle should support package for the ivy ones. So this plugin is not aware of those details

**Comment by rpalcolea** [comment]
Opened pull request for this https://github.com/jenkinsci/gradle-jpi-plugin/pull/144

**Comment by jjohannes** [comment]
Thanks for the PR @rpalcolea. I think it is the right fix.
