### ISSUE TITLE
Consider rollback jenkins configurations and mark them as deprecated

### ISSUE THREAD

**Issue by rpalcolea** [jenkinsci/gradle-jpi-plugin#149]
Hi folks,

I was looking at removals for the next version:

```
Removed
jenkinsPlugins configuration (use implementation)
optionalJenkinsPlugins configuration (use Gradle feature variants)
jenkinsTest configuration (use testImplementation)
```

Wondering if this could be added back and extend those configurations instead and have them as deprecated for a while so folks can move on their own pace instead of introducing the breaking change?

Thoughts? // cc @rahulsom

**Comment by sghill** [comment]
Definitely worth considering. The change in `optionalJenkinsPlugins` doesn’t have a straightforward path forward without breaking, but the other two do. The original discussion was here: https://github.com/jenkinsci/gradle-jpi-plugin/pull/132#issuecomment-577621057

Considering the impact of this breaking change was mentioned here as a reason to publish the candidates: https://github.com/jenkinsci/gradle-jpi-plugin/pull/132#discussion_r372559202

One other thing worth considering is if it’s simpler/faster to define the configuration inheritance in an intermediate plugin.

**Comment by rahulsom** [comment]
The warning idea sounds good, but this is a 0.x plugin, so I wouldn't want to burden it with having to maintain backwards compatibility. I wonder if there is a way to break the build and explain the new approach at the same time...

**Comment by rpalcolea** [comment]
configurations could be restored but fail the build when used

**Comment by wolfs** [comment]
> configurations could be restored but fail the build when used

I don't see this a big improvement, given that in the current state the build fails as well.

Regarding backwards compatibility: The RC candidate currently only works on Gradle 6.0. Is this also a problem? Or is it enough to have the old configurations working for a few more releases until they are removed?

**Comment by rpalcolea** [comment]
It is more of a migration other than gradle compatibility + error messaging could be more helpful than configuration not found, with plugin specifics on how to migrate

**Comment by rpalcolea** [comment]
This is what I had in mind: https://github.com/jenkinsci/gradle-jpi-plugin/pull/150
