### ISSUE TITLE
:server task fails when kotlin multiplatform dependencies are used

### ISSUE THREAD

**Issue by matejdro** [jenkinsci/gradle-jpi-plugin#153]
1. Extract [okio-test.zip](https://github.com/jenkinsci/gradle-jpi-plugin/files/4305691/okio-test.zip)   somewhere
2. Run `gradlew server`

Task will fail with following exception:

```
Execution failed for task ':server'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve com.squareup.okio:okio:2.4.3.
     Required by:
         project :
      > Cannot choose between the following variants of com.squareup.okio:okio:2.4.3:
          - jpiEmpty
          - jvm-api
          - jvm-runtime
          - metadata-api
        All of them match the consumer attributes:
          - Variant 'jpiEmpty' capability com.squareup.okio:okio:2.4.3:
              - Unmatched attributes:
                  - Found empty-jpi 'true' but wasn't required.
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.dependency.bundling 'external' but wasn't required.
                  - Found org.gradle.libraryelements 'jpi' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime' but wasn't required.
          - Variant 'jvm-api' capability com.squareup.okio:okio:2.4.3:
              - Unmatched attributes:
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-api' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'jvm-runtime' capability com.squareup.okio:okio:2.4.3:
              - Unmatched attributes:
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'metadata-api' capability com.squareup.okio:okio:2.4.3:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'kotlin-api' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
```

Issue seems similar to the [issue in kapt plugin that was fixed a while ago](https://youtrack.jetbrains.com/issue/KT-31641).

**Comment by matejdro** [comment]
Even worse, since configuration is detached, there appears to be no way to get it in build.gradle file and thus you cannot apply workaround mentioned in the kapt issue linked above.

**Comment by sghill** [comment]
Thanks for trying this out @matejdro. The attached example and linked issues are very useful.

This is the first case I know of using Kotlin multiplatform dependencies in a Jenkins plugin.

Starting to take a look at this, but also want to include @jjohannes.

**Comment by sghill** [comment]
Hi @matejdro,

In #155 I added a couple tests based on your example project. Both failed initially, but succeeded after adding the workaround you mentioned above. I'm planning on leaving this PR open until midweek to allow for comments or alternative approaches. I'll comment here again once this has been published in another rc.

In the meantime it looks like kotlin multiplatform dependencies work with the latest release of this plugin: 0.38.0.

**Comment by matejdro** [comment]
I'm not that well versed in the gradle stuff unfortunately, so I cannot make any comments on PR.

**Comment by sghill** [comment]
[0.39.0-rc.6](https://github.com/jenkinsci/gradle-jpi-plugin/releases/tag/v0.39.0-rc.6) was published as a pre-release today with a fix for this.

**Comment by matejdro** [comment]
Thanks, it works!
