### ISSUE TITLE
FileNotFoundException when downloading plugin after releasing via JPI 0.39.0

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/gradle-jpi-plugin#158]
Hello! 

Thanks for the great work on this plugin. 

After upgrading to 0.39.0 and releasing my plugin i'm experiencing:

~~~
java.io.FileNotFoundException: http://archives.jenkins-ci.org/plugins/templating-engine/1.6/templating-engine.hpi
~~~

when trying to download in the update center. 

Logs from the publish command: 

~~~
./gradlew publish                                          

> Task :publishMavenJpiPublicationToJenkinsRepository
Cannot upload checksum for module-maven-metadata.xml. Remote repository doesn't support sha-256. Error: Could not PUT 'https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/templating-engine/maven-metadata.xml.sha256'. Received status code 403 from server: Forbidden
Cannot upload checksum for module-maven-metadata.xml. Remote repository doesn't support sha-512. Error: Could not PUT 'https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/templating-engine/maven-metadata.xml.sha512'. Received status code 403 from server: Forbidden

BUILD SUCCESSFUL in 13s
12 actionable tasks: 8 executed, 4 up-to-date
~~~

Any thoughts as to what could be causing this? 

output from `./gradlew --version`:

~~~
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.14.6 x86_64
~~~

**Comment by steven-terrana** [comment]
I will try disabling the SHA-256 and SHA-512 metadata

**Comment by steven-terrana** [comment]
It seems i jumped the gun on this issue. 

Though the new release showed in repo.jenkins-ci.org, it had not yet made it's way to the archive site. 

After some time, it synchronized and everything started working. 

I will close this issue - thank you again for your work on this plugin.

**Comment by sghill** [comment]
Thanks for the kindness @steven-terrana. I appreciate you following up with the solution.

The sha256/512 warning is a good callout. I should get disabling sha256 and sha512 into the docs until the public repo supports it.

**Comment by steven-terrana** [comment]
@sghill - i have opened a PR documenting this in the README. 

https://github.com/jenkinsci/gradle-jpi-plugin/pull/159

hope this helps!

**Comment by daniel-beck** [comment]
Could you please file an INFRA issue in Jira and assign it to me with a complete list of these files that would need to be published? We restrict paths to prevent malicious or accidental broken uploads, and it's probably just a matter of whitelisting these paths.

**Comment by sghill** [comment]
I opened [INFRA-2594](https://issues.jenkins-ci.org/browse/INFRA-2594) - Thanks @daniel-beck.
