### ISSUE TITLE
No support for @Restricted annotations

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/gradle-jpi-plugin#160]
Plugins built with Gradle appear to ignore `@Restricted` annotations from https://github.com/kohsuke/access-modifier/

This is dangerous as it invites the use of APIs not intended to be used outside core (or plugins) _at all_, leading to binary compatibility issues when they're changed.

**Comment by sghill** [comment]
Thanks @daniel-beck, I wasn't aware of this. I agree we should add support for Restricted. It may take some time.

I found [these jenkins.io docs](https://jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/#restricted-annotations) and [javadoc on types of restrictions](https://kohsuke.org/access-modifier/apidocs/index.html). `org.kohsuke:access-modifier-checker` provides a MOJO that delegates to [`Checker`](https://github.com/kohsuke/access-modifier/blob/master/access-modifier-checker/src/main/java/org/kohsuke/accmod/impl/Checker.java). I did a quick spike attempting to use `Checker` but wasn't successful.
