### ISSUE TITLE
Plugin description doesn't seem to be getting set

### ISSUE THREAD

**Issue by c4milo** [jenkinsci/gradle-jpi-plugin#168]
It is currently adding a "random" description: "Trilead API Plugin provides the Trilead library to any dependent plugins in an easily update-able manner."

**Comment by sghill** [comment]
Is this the description on the generated POM? That should be the [project's description](https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizer.groovy#L44). It has [a couple tests here](https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizerIntegrationSpec.groovy#L74).

What is the value of `description` from running `./gradlew properties`?

**Comment by c4milo** [comment]
```
description: Plugin to publish pipeline metadata to a Grafeas server
```

**Comment by c4milo** [comment]
<img width="1047" alt="Screen Shot 2020-09-08 at 2 22 09 PM" src="https://user-images.githubusercontent.com/41681/92531505-63677a80-f1fc-11ea-98a4-edec033f2f46.png">

**Comment by sghill** [comment]
Could you provide an example that reproduces this problem? I see [trilead-api](https://plugins.jenkins.io/trilead-api/), but it doesn't look like Grafeas is open source.

**Comment by sghill** [comment]
Hi @c4milo, I'm going to close this due to inactivity. Happy to reopen and take a look if you'd like to share an example that reproduces the problem.
