### ISSUE TITLE
jenkinsServer doesn't upgrade installed dependencies

### ISSUE THREAD

**Issue by c4milo** [jenkinsci/gradle-jpi-plugin#169]
This doesn't seem to be working, assuming the scope of `jenkinsServer` covers this use case.

**Comment by sghill** [comment]
Thanks for the report, @c4milo. Which version of the jpi-plugin? Can you describe a bit more about the scenario?

Today the current task installs plugins (and transitive plugin dependencies) at the version specified on the configuration. You should be able to get the latest published version of those plugins by declaring the version as `latest.release`.

**Comment by c4milo** [comment]
hey @sghill, thanks for getting back. This seemed to have been transient, it is now working just fine! Thank you!
