### ISSUE TITLE
Rejection of new hosting requests using the Gradle JPI plugin

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/gradle-jpi-plugin#213]
Hey,

I would like to let you know that the hosting team plans to reject new hosting requests using the Gradle JPI plugin. Existing plugins are unaffected by this change. The hosting team would then recommend to use maven as build tool.

There are several reasons why we would like to reject new hosting requests using the JPI plugin
(this is a non-exhaustive list of topics I am aware about, there are possibly more items to add by other people):
- No support for [JEP-229](https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc)
- No support for [JEP-305](https://github.com/jenkinsci/jep/tree/master/jep/305)
- Lacking end-user documentation on [jenkins.io](https://www.jenkins.io/doc/developer/publishing/releasing/)
- No support for publishing static analysis and coverage reports on ci.jenkins.io
- No support for building on ACI (Azure Container Instance) agents
- Suspect to produce invalid pom.xml files causing issues with third parties and the update center in the past

We want to provide people a good experience and access to all tools possible, when we host their plugins. Given, the JPI plugin is very limiting, and we see no ongoing efforts to support the same scope maven has, we would like to advise new hosting requestors to use maven.

Once all points above are addressed, we are happily looking into to accept new hosting requests using the JPI plugin again.

Taking the positive feedback on the [mailing list](https://groups.google.com/g/jenkinsci-dev/c/lHQAiEepBiw) into consideration, I would like to go ahead with this item soon.

~ Alex, for the hosting team

**Comment by timja** [comment]
cc @sghill @c00ler

**Comment by sghill** [comment]
@NotMyFault Thanks for letting me know. The most recent OSS plugin I started used maven as well to take advantage of all the great work the community has done here, so I definitely understand.

My priorities for maintaining this plugin are primarily Gradle compatibility, as I have several closed source plugins and we use Gradle internally. In this regard, the plugin is in great shape. We have 476 acceptance tests that can easily be run against any version of Gradle (including pre-releases) and any version of Java.

I don't intend to work on this in the near future, though I would support anyone else who wanted to. To that end, I will create issues for these and wrap them up into an "accept hosting requests" milestone.

I did want to outline what I thought would address these issues and ask a question to make sure I understand first though.

I believe these amount to configuring built-in features of Gradle:

> No support for [JEP-229](https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc)
> No support for [JEP-305](https://github.com/jenkinsci/jep/tree/master/jep/305)

These could be supported by adding the expected version format and creating/updating a shared library to publish.

> No support for publishing static analysis and coverage reports on ci.jenkins.io

Spotbugs, pmd, checkstyle all have plugins that could be run through the shared library.

> Suspect to produce invalid pom.xml files causing issues with third parties and the update center in the past

Is there a place I can read more about this? I'm not sure why it wouldn't work as-is. Gradle is able to bootstrap, resolve dependencies and build so long as java is present.

> Suspect to produce invalid pom.xml files causing issues with third parties and the update center in the past

I believe this was fixed in v0.31.0 on April 1, 2019 as https://github.com/jenkinsci/gradle-jpi-plugin/commit/792be79d9e7b5d69b04733827bb45b91a7c095b4.

**Comment by NotMyFault** [comment]
Thanks for sharing your insights. We've disabled the Gradle checker from the hosting tool a few days ago.

**Comment by sghill** [comment]
I know it's rarely easy to end support for something, but I wanted to say I do appreciate the clear and thoughtful communication. Thanks for taking the time to create an issue here with links for more context @NotMyFault. Also thank you for the ping @timja.

I have defined a [new milestone for hosting support](https://github.com/jenkinsci/gradle-jpi-plugin/milestone/10) with attached issues mentioned here. I have also updated the README with a warning near the top to give users more context. I believe that takes care of the action items here, so I'll close this one out.

**Comment by alextu** [comment]
@NotMyFault a new JPI plugin version was released by @sghill that brings building blocks for publishing incrementals and quality checks. That being said, afaiu it would require some glue in `buildPluginWithGradle.groovy` to support incrementals and report quality checks on https://ci.jenkins.io. Is it something you're willing to take on your side ?

**Comment by alextu** [comment]
Thanks, I've submitted some PRs to support quality checks and incrementals, waiting for your reviews 😄

**Comment by alextu** [comment]
Regarding 
> Lacking end-user documentation on [jenkins.io](https://www.jenkins.io/doc/developer/publishing/releasing/)

I think there are 3 use cases:
- publishing incrementals when building on [jenkins](https://ci.jenkins.io), nothing to do except upgrading the JPI plugin, I can document this, but wonder where ?
- publishing incrementals when building "manually", this is documented in the [JPI plugin readme](https://github.com/jenkinsci/gradle-jpi-plugin/#using-jenkins-incrementals-repository)
- publishing incrementals continuously as releases with Github actions, this is actually not supported by the current Github action for Gradle builds, see https://github.com/jenkins-infra/jenkins-maven-cd-action/blob/master/run.sh). As a side note, I wonder why this wasn't handled by promoting artifacts from the incrementals repository to the releases repository (to avoid rebuilding).

**Comment by timja** [comment]
> publishing incrementals when building on [jenkins](https://ci.jenkins.io/), nothing to do except upgrading the JPI plugin, I can document this, but wonder where ?

Probably a post on the developers mailing list / at least in release notes

> publishing incrementals continuously as releases with Github actions, this is actually not supported by the current Github action for Gradle builds

once supported instructions should probably go on jenkins.io as maven ones are there

**Comment by Stephan-8** [comment]
https://github.com/jenkinsci/gradle-jpi-plugin/issues/213#issue-1499881868

**Comment by Stephan-8** [comment]
[]plugins {
  id 'org.jenkins-ci.jpi' version '0.52.0'
}

group = 'org.jenkins-ci.plugins'
version = '1.2.0-SNAPSHOT'
description = 'A description of your plugin'

jenkinsPlugin {
    // version of Jenkins core this plugin depends on, must be 1.420 or later
    jenkinsVersion = '1.420'

    // ID of the plugin, defaults to the project name without trailing '-plugin'
    shortName = 'hello-world'

    // human-readable name of plugin
    displayName = 'Hello World plugin built with Gradle'

    // URL for plugin on Jenkins wiki or elsewhere
    url = 'http://wiki.jenkins-ci.org/display/JENKINS/SomePluginPage'

    // plugin URL on GitHub, optional
    gitHubUrl = 'https://github.com/jenkinsci/some-plugin'
  
    // scm tag eventually set in the published pom, optional
    scmTag = 'v1.0.0'

    // use the plugin class loader before the core class loader, defaults to false
    pluginFirstClassLoader = true

    // optional list of package prefixes that your plugin doesn't want to see from core
    maskClasses = 'groovy.grape org.apache.commons.codec'

    // optional version number from which this plugin release is configuration-compatible
    compatibleSinceVersion = '1.1.0'

    // set the directory from which the development server will run, defaults to 'work'
    workDir = file('/tmp/jenkins')

    // URL used to deploy the plugin, defaults to the value shown
    // the system property 'jpi.repoUrl' can be used to override this option
    repoUrl = 'https://repo.jenkins-ci.org/releases'

    // URL used to deploy snapshots of the plugin, defaults to the value shown
    // the system property 'jpi.snapshotRepoUrl' can be used to override this option
    snapshotRepoUrl = 'https://repo.jenkins-ci.org/snapshots'

    // enable injection of additional tests for checking the syntax of Jelly and other things
    disabledTestInjection = false

    // the output directory for the localizer task relative to the project root, defaults to the value shown
    localizerOutputDir = "${project.buildDir}/generated-src/localizer"

    // disable configuration of Maven Central, the local Maven cache and the Jenkins Maven repository, defaults to true
    configureRepositories = false

    // skip configuration of publications and repositories for the Maven Publishing plugin, defaults to true
    configurePublishing = false

    // plugin file extension, either 'jpi' or 'hpi', defaults to 'hpi'
    fileExtension = 'hpi'

    // the developers section is optional, and corresponds to the POM developers section
    developers {
        developer {
            id 'abayer'
            name 'Andrew Bayer'
            email 'andrew.bayer@gmail.com'
        }
    }

    // the licenses section is optional, and corresponds to the POM licenses section
    licenses {
        license {
            name 'Apache License, Version 2.0'
            url 'https://www.apache.org/licenses/LICENSE-2.0.txt'
            distribution 'repo'
            comments 'A business-friendly OSS license'
        }
    }

    // Git based version generation is optional
    gitVersion {
        // Don't fail if changes are not committed (default: false)
        allowDirty = true
        // Customize version format (default: %d.%s where %d is the commit depth, %s the abbreviated sha)
        versionFormat = 'rc-%d.%s'
        // Sanitize the hash according to Jenkins requirements (default: false)  
        sanitize = true 
        // Customize abbreviated sha length (default: 12)
        abbrevLength = 10
        // Customize git root (default: project directory)
        gitRoot = file('/some/external/git/repo')
    }

    // "Incrementals" custom repository (default: https://repo.jenkins-ci.org/incrementals)
    incrementalsRepoUrl = 'https://custom'

    // Enable quality check plugins
    enableSpotBugs()
    enableCheckstyle()
    enableJacoco()
}plugins {
  id 'org.jenkins-ci.jpi' version '0.52.0'
}

group = 'org.jenkins-ci.plugins'
version = '1.2.0-SNAPSHOT'
description = 'A description of your plugin'

jenkinsPlugin {
    // version of Jenkins core this plugin depends on, must be 1.420 or later
    jenkinsVersion = '1.420'

    // ID of the plugin, defaults to the project name without trailing '-plugin'
    shortName = 'hello-world'

    // human-readable name of plugin
    displayName = 'Hello World plugin built with Gradle'

    // URL for plugin on Jenkins wiki or elsewhere
    url = 'http://wiki.jenkins-ci.org/display/JENKINS/SomePluginPage'

    // plugin URL on GitHub, optional
    gitHubUrl = 'https://github.com/jenkinsci/some-plugin'
  
    // scm tag eventually set in the published pom, optional
    scmTag = 'v1.0.0'

    // use the plugin class loader before the core class loader, defaults to false
    pluginFirstClassLoader = true

    // optional list of package prefixes that your plugin doesn't want to see from core
    maskClasses = 'groovy.grape org.apache.commons.codec'

    // optional version number from which this plugin release is configuration-compatible
    compatibleSinceVersion = '1.1.0'

    // set the directory from which the development server will run, defaults to 'work'
    workDir = file('/tmp/jenkins')

    // URL used to deploy the plugin, defaults to the value shown
    // the system property 'jpi.repoUrl' can be used to override this option
    repoUrl = 'https://repo.jenkins-ci.org/releases'

    // URL used to deploy snapshots of the plugin, defaults to the value shown
    // the system property 'jpi.snapshotRepoUrl' can be used to override this option
    snapshotRepoUrl = 'https://repo.jenkins-ci.org/snapshots'

    // enable injection of additional tests for checking the syntax of Jelly and other things
    disabledTestInjection = false

    // the output directory for the localizer task relative to the project root, defaults to the value shown
    localizerOutputDir = "${project.buildDir}/generated-src/localizer"

    // disable configuration of Maven Central, the local Maven cache and the Jenkins Maven repository, defaults to true
    configureRepositories = false

    // skip configuration of publications and repositories for the Maven Publishing plugin, defaults to true
    configurePublishing = false

    // plugin file extension, either 'jpi' or 'hpi', defaults to 'hpi'
    fileExtension = 'hpi'

    // the developers section is optional, and corresponds to the POM developers section
    developers {
        developer {
            id 'abayer'
            name 'Andrew Bayer'
            email 'andrew.bayer@gmail.com'
        }
    }

    // the licenses section is optional, and corresponds to the POM licenses section
    licenses {
        license {
            name 'Apache License, Version 2.0'
            url 'https://www.apache.org/licenses/LICENSE-2.0.txt'
            distribution 'repo'
            comments 'A business-friendly OSS license'
        }
    }

    // Git based version generation is optional
    gitVersion {
        // Don't fail if changes are not committed (default: false)
        allowDirty = true
        // Customize version format (default: %d.%s where %d is the commit depth, %s the abbreviated sha)
        versionFormat = 'rc-%d.%s'
        // Sanitize the hash according to Jenkins requirements (default: false)  
        sanitize = true 
        // Customize abbreviated sha length (default: 12)
        abbrevLength = 10
        // Customize git root (default: project directory)
        gitRoot = file('/some/external/git/repo')
    }

    // "Incrementals" custom repository (default: https://repo.jenkins-ci.org/incrementals)
    incrementalsRepoUrl = 'https://custom'

    // Enable quality check plugins
    enableSpotBugs()
    enableCheckstyle()
    enableJacoco()
}url)
