### ISSUE TITLE
Localizer task @InputFiles not configured

### ISSUE THREAD

**Issue by quidryan** [jenkinsci/gradle-jpi-plugin#3]
Localizer task is relying on GeneratorTask to find all the files and determine which files have changed. But this leaves Gradle out of the loop, this is typically solved by specifying @InputFiles so that gradle knows when the task is UP-TO-DATE. Because there's no input, only looks for the existence of the @OutputFiles. Which means that it'll only run the localizer task once, until a clean is done.

This fix is to specify the inputs to the task.

**Comment by sghill** [comment]
Closing this issue as it was fixed in 2c095364bf1e3efd1d0ca3b16aadcf90c8f7a635.
